version: '3.2'

services:

  mongodb:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    container_name: mongodb

  app:
    image: firstapp
    ports:
      - 8080:8080
    depends_on: 
      - mongodb
    container_name: app_on_docker

